ifndef W98_DECOMP_DIR
$(error Error getting decompilation path. Try running "InstallEnvironment.bat")
endif

NAME = wb16off
SDK = VC10
OUT = EXE
SUBSYSTEM = DOS

TYPE = DISC
DISC_LOCATION = win98/

SOURCES = wb16off.obj

include $(W98_DECOMP_TOOLS_DIR)\buildrules


